--
-- PostgreSQL database dump
--

\restrict B7mXd0OzeRtiyxGyfitbnaAnPmWeGCuF0Ff9btookWpeDbxhuztW4vAhfyd3HnD

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-16 06:31:30

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 17794)
-- Name: auth; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA auth;


ALTER SCHEMA auth OWNER TO postgres;

--
-- TOC entry 6 (class 2615 OID 17793)
-- Name: finances; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA finances;


ALTER SCHEMA finances OWNER TO postgres;

--
-- TOC entry 8 (class 2615 OID 17795)
-- Name: users; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA users;


ALTER SCHEMA users OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 233 (class 1259 OID 17939)
-- Name: RefreshTokens; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."RefreshTokens" (
    "RefreshTokenId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Revoked" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE auth."RefreshTokens" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17957)
-- Name: TwoFactorCodes; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."TwoFactorCodes" (
    "TwoFactorCodeId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Code" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "TwoFactorStatusId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE auth."TwoFactorCodes" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17853)
-- Name: TwoFactorStatus; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."TwoFactorStatus" (
    "TwoFactorStatusId" integer NOT NULL,
    "Status" character varying(50) NOT NULL
);


ALTER TABLE auth."TwoFactorStatus" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 17852)
-- Name: TwoFactorStatus_TwoFactorStatusId_seq; Type: SEQUENCE; Schema: auth; Owner: postgres
--

ALTER TABLE auth."TwoFactorStatus" ALTER COLUMN "TwoFactorStatusId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth."TwoFactorStatus_TwoFactorStatusId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 17796)
-- Name: AccountTypes; Type: TABLE; Schema: finances; Owner: postgres
--

CREATE TABLE finances."AccountTypes" (
    "AccountTypeId" uuid NOT NULL,
    "Name" character varying(25) NOT NULL,
    "Abbre" character varying(9) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE finances."AccountTypes" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17875)
-- Name: Accounts; Type: TABLE; Schema: finances; Owner: postgres
--

CREATE TABLE finances."Accounts" (
    "AccountId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AccountTypeId" uuid NOT NULL,
    "CurrecyId" uuid NOT NULL,
    "BankId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" character varying(150) NOT NULL,
    "Balance" double precision NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE finances."Accounts" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17805)
-- Name: Banks; Type: TABLE; Schema: finances; Owner: postgres
--

CREATE TABLE finances."Banks" (
    "BankId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Abbre" character varying(10) NOT NULL,
    "TransferFee" double precision NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE finances."Banks" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17911)
-- Name: Categories; Type: TABLE; Schema: finances; Owner: postgres
--

CREATE TABLE finances."Categories" (
    "CategoryId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ParentId" uuid,
    "NatureId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" character varying(150) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE finances."Categories" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17817)
-- Name: Currencies; Type: TABLE; Schema: finances; Owner: postgres
--

CREATE TABLE finances."Currencies" (
    "CurrecyId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Code" character varying(3) NOT NULL,
    "Symbol" character varying(3) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE finances."Currencies" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 17829)
-- Name: Natures; Type: TABLE; Schema: finances; Owner: postgres
--

CREATE TABLE finances."Natures" (
    "NatureId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Abbre" character varying(5) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE finances."Natures" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17840)
-- Name: TransactionTypes; Type: TABLE; Schema: finances; Owner: postgres
--

CREATE TABLE finances."TransactionTypes" (
    "TransactionTypeId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "CurrentValue" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE finances."TransactionTypes" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17980)
-- Name: Transactions; Type: TABLE; Schema: finances; Owner: postgres
--

CREATE TABLE finances."Transactions" (
    "TransactionId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TransactionTypeId" uuid NOT NULL,
    "CategoryId" uuid NOT NULL,
    "AccountId" uuid NOT NULL,
    "Amount" double precision NOT NULL,
    "Description" character varying(500) NOT NULL,
    "TransferGroupID" uuid,
    "TransactionDate" timestamp with time zone NOT NULL,
    "Reference" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE finances."Transactions" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17786)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17860)
-- Name: Users; Type: TABLE; Schema: users; Owner: postgres
--

CREATE TABLE users."Users" (
    "UserId" uuid CONSTRAINT "Users_UserID_not_null" NOT NULL,
    "Email" character varying(150) NOT NULL,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE users."Users" OWNER TO postgres;

--
-- TOC entry 5123 (class 0 OID 17939)
-- Dependencies: 233
-- Data for Name: RefreshTokens; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."RefreshTokens" ("RefreshTokenId", "UserId", "Token", "ExpiresAt", "Revoked", "CreatedAt") FROM stdin;
69d5d81e-0b5b-4117-912b-4edb0b3a907a	34f135d7-718a-4d28-a06f-333c2354c813	HkuTj79oTmMVBZC/dpcdUBBXBBpJJYnYOyDLIKKaG+jj0eNORIlnm3ZjsOGje2VOZPwlzJanqNdQ15L6OzJVqg==	2026-03-22 23:31:03.642523-06	f	2026-03-15 23:31:03.642613-06
c33b54a4-3713-4a50-be48-047dbeec4d48	34f135d7-718a-4d28-a06f-333c2354c813	zgu7Vh5ItwXJWta/2AtemOORFpvyYUz95WJ1GDUxAwmCbeUBafSJMvEsOHH5GN6Csyu54DLU152kJqaxAMa9YQ==	2026-03-23 06:17:47.703874-06	f	2026-03-16 06:17:47.704019-06
\.


--
-- TOC entry 5124 (class 0 OID 17957)
-- Dependencies: 234
-- Data for Name: TwoFactorCodes; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."TwoFactorCodes" ("TwoFactorCodeId", "UserId", "Code", "ExpiresAt", "TwoFactorStatusId", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 5119 (class 0 OID 17853)
-- Dependencies: 229
-- Data for Name: TwoFactorStatus; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."TwoFactorStatus" ("TwoFactorStatusId", "Status") FROM stdin;
1	Active
2	Used
3	Expired
4	Replaced
\.


--
-- TOC entry 5113 (class 0 OID 17796)
-- Dependencies: 223
-- Data for Name: AccountTypes; Type: TABLE DATA; Schema: finances; Owner: postgres
--

COPY finances."AccountTypes" ("AccountTypeId", "Name", "Abbre", "CreatedAt") FROM stdin;
33bd93c8-eec4-406a-9619-ff3af41bc799	Debit	TYPE-DEBT	2026-03-16 06:16:55.000547-06
99f16153-db8f-412e-a7af-437fe62c7f33	Cash	TYPE-CASH	2026-03-16 06:16:55.000547-06
b1528456-c62e-4b45-9aa2-f9b8fa22bca0	Investment	TYPE-INVS	2026-03-16 06:16:55.000547-06
e635117b-0551-40fa-afb1-5389cfcd3ce2	Savings	TYPE-SAVS	2026-03-16 06:16:55.000547-06
\.


--
-- TOC entry 5121 (class 0 OID 17875)
-- Dependencies: 231
-- Data for Name: Accounts; Type: TABLE DATA; Schema: finances; Owner: postgres
--

COPY finances."Accounts" ("AccountId", "UserId", "AccountTypeId", "CurrecyId", "BankId", "Name", "Description", "Balance", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 5114 (class 0 OID 17805)
-- Dependencies: 224
-- Data for Name: Banks; Type: TABLE DATA; Schema: finances; Owner: postgres
--

COPY finances."Banks" ("BankId", "Name", "Abbre", "TransferFee", "CreatedAt") FROM stdin;
8ec5eab9-3a72-40b2-8746-b94e2ab3579b	BANCO DE AMERICA	BAC	2	2026-03-16 06:16:55.000398-06
90d3db5d-0c60-462a-93c9-3f0bd46c642f	BANCO DE LA PRODUCCION	BANPRO	2	2026-03-16 06:16:55.000398-06
\.


--
-- TOC entry 5122 (class 0 OID 17911)
-- Dependencies: 232
-- Data for Name: Categories; Type: TABLE DATA; Schema: finances; Owner: postgres
--

COPY finances."Categories" ("CategoryId", "UserId", "ParentId", "NatureId", "Name", "Description", "CreatedAt") FROM stdin;
4ead4578-1eb2-4b46-a37f-450dd2039746	34f135d7-718a-4d28-a06f-333c2354c813	\N	4477b269-2acb-4649-9560-e9d09191b588	Salario	Salario Mensual 	2026-03-16 06:18:21.607277-06
699ea41c-568e-4156-bc9a-1e5037820d0e	34f135d7-718a-4d28-a06f-333c2354c813	4ead4578-1eb2-4b46-a37f-450dd2039746	4477b269-2acb-4649-9560-e9d09191b588	Salario Básico	Salario básico, no incluye deducciones y percepciones	2026-03-16 06:22:53.029328-06
f528b3bb-e387-48e7-b1af-e866cfc479c8	34f135d7-718a-4d28-a06f-333c2354c813	4ead4578-1eb2-4b46-a37f-450dd2039746	4477b269-2acb-4649-9560-e9d09191b588	Salario Bruto	Salario principal, incluye percepciones, no incluye deducciones	2026-03-16 06:23:43.16147-06
b9910409-dc9c-4bb5-a100-bfc8dcaf5d74	34f135d7-718a-4d28-a06f-333c2354c813	4ead4578-1eb2-4b46-a37f-450dd2039746	4477b269-2acb-4649-9560-e9d09191b588	Salario Neto	Salario bruto - despues de deducciones	2026-03-16 06:24:18.777157-06
\.


--
-- TOC entry 5115 (class 0 OID 17817)
-- Dependencies: 225
-- Data for Name: Currencies; Type: TABLE DATA; Schema: finances; Owner: postgres
--

COPY finances."Currencies" ("CurrecyId", "Name", "Code", "Symbol", "CreatedAt") FROM stdin;
1424bdef-0fa6-4e2a-a52b-c6d43d25df96	Cordoba Nicaraguense	NIO	C$	2026-03-16 06:16:55.000449-06
31e3c165-a6c6-4f84-9f6a-2159ba16a29e	Dolar Estadounidense	USD	$	2026-03-16 06:16:55.000448-06
f39e961f-b290-4559-91e5-2fe47e4e424d	Euro	EUR	€	2026-03-16 06:16:55.000449-06
\.


--
-- TOC entry 5116 (class 0 OID 17829)
-- Dependencies: 226
-- Data for Name: Natures; Type: TABLE DATA; Schema: finances; Owner: postgres
--

COPY finances."Natures" ("NatureId", "Name", "Abbre", "CreatedAt") FROM stdin;
4477b269-2acb-4649-9560-e9d09191b588	Income	I	2026-03-16 06:16:55.000351-06
b1153a41-286d-4fe7-88da-1604d4ddf8ec	Expenses	E	2026-03-16 06:16:55.000352-06
\.


--
-- TOC entry 5117 (class 0 OID 17840)
-- Dependencies: 227
-- Data for Name: TransactionTypes; Type: TABLE DATA; Schema: finances; Owner: postgres
--

COPY finances."TransactionTypes" ("TransactionTypeId", "Name", "Code", "CurrentValue", "CreatedAt") FROM stdin;
1419b9a1-8119-418e-a679-90f4794b9b06	Income	INC	0	2026-03-16 06:16:55.000503-06
959bde9a-1eb6-47e0-9977-fb10ebd606a4	Transfers	TRF	0	2026-03-16 06:16:55.000504-06
b158f17a-9967-434f-b5a9-3c499688966e	Expenses	EXP	0	2026-03-16 06:16:55.000503-06
\.


--
-- TOC entry 5125 (class 0 OID 17980)
-- Dependencies: 235
-- Data for Name: Transactions; Type: TABLE DATA; Schema: finances; Owner: postgres
--

COPY finances."Transactions" ("TransactionId", "UserId", "TransactionTypeId", "CategoryId", "AccountId", "Amount", "Description", "TransferGroupID", "TransactionDate", "Reference", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 5112 (class 0 OID 17786)
-- Dependencies: 222
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260316052932_new_initial_again_4times3	8.0.24
20260316053033_new_initial_again_4times33	8.0.24
20260316121655_new_initial_again_4times4	8.0.24
\.


--
-- TOC entry 5120 (class 0 OID 17860)
-- Dependencies: 230
-- Data for Name: Users; Type: TABLE DATA; Schema: users; Owner: postgres
--

COPY users."Users" ("UserId", "Email", "Username", "PasswordHash", "FullName", "IsActive", "TwoFactorEnabled", "CreatedAt") FROM stdin;
34f135d7-718a-4d28-a06f-333c2354c813	edwincruz130691@gmail.com	Egeminis13	$2a$11$3PBhwA36Z66ScV2e6OJdnOx/2KDtdUO2OxLrwG2V19KHmN4skTThq	Edwin Cruz	t	f	2026-03-15 23:30:55.69251-06
\.


--
-- TOC entry 5131 (class 0 OID 0)
-- Dependencies: 228
-- Name: TwoFactorStatus_TwoFactorStatusId_seq; Type: SEQUENCE SET; Schema: auth; Owner: postgres
--

SELECT pg_catalog.setval('auth."TwoFactorStatus_TwoFactorStatusId_seq"', 5, false);


--
-- TOC entry 4939 (class 2606 OID 17951)
-- Name: RefreshTokens PK_RefreshTokens; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."RefreshTokens"
    ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("RefreshTokenId");


--
-- TOC entry 4943 (class 2606 OID 17969)
-- Name: TwoFactorCodes PK_TwoFactorCodes; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."TwoFactorCodes"
    ADD CONSTRAINT "PK_TwoFactorCodes" PRIMARY KEY ("TwoFactorCodeId");


--
-- TOC entry 4921 (class 2606 OID 17859)
-- Name: TwoFactorStatus PK_TwoFactorStatus; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."TwoFactorStatus"
    ADD CONSTRAINT "PK_TwoFactorStatus" PRIMARY KEY ("TwoFactorStatusId");


--
-- TOC entry 4910 (class 2606 OID 17804)
-- Name: AccountTypes PK_AccountTypes; Type: CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."AccountTypes"
    ADD CONSTRAINT "PK_AccountTypes" PRIMARY KEY ("AccountTypeId");


--
-- TOC entry 4930 (class 2606 OID 17890)
-- Name: Accounts PK_Accounts; Type: CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Accounts"
    ADD CONSTRAINT "PK_Accounts" PRIMARY KEY ("AccountId");


--
-- TOC entry 4912 (class 2606 OID 17816)
-- Name: Banks PK_Banks; Type: CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Banks"
    ADD CONSTRAINT "PK_Banks" PRIMARY KEY ("BankId");


--
-- TOC entry 4935 (class 2606 OID 17923)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId");


--
-- TOC entry 4914 (class 2606 OID 17828)
-- Name: Currencies PK_Currencies; Type: CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Currencies"
    ADD CONSTRAINT "PK_Currencies" PRIMARY KEY ("CurrecyId");


--
-- TOC entry 4916 (class 2606 OID 17839)
-- Name: Natures PK_Natures; Type: CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Natures"
    ADD CONSTRAINT "PK_Natures" PRIMARY KEY ("NatureId");


--
-- TOC entry 4919 (class 2606 OID 17851)
-- Name: TransactionTypes PK_TransactionTypes; Type: CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."TransactionTypes"
    ADD CONSTRAINT "PK_TransactionTypes" PRIMARY KEY ("TransactionTypeId");


--
-- TOC entry 4950 (class 2606 OID 17996)
-- Name: Transactions PK_Transactions; Type: CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Transactions"
    ADD CONSTRAINT "PK_Transactions" PRIMARY KEY ("TransactionId");


--
-- TOC entry 4908 (class 2606 OID 17792)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4924 (class 2606 OID 17874)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: users; Owner: postgres
--

ALTER TABLE ONLY users."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("UserId");


--
-- TOC entry 4936 (class 1259 OID 18024)
-- Name: IX_RefreshTokens_Token; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON auth."RefreshTokens" USING btree ("Token");


--
-- TOC entry 4937 (class 1259 OID 18025)
-- Name: IX_RefreshTokens_UserId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_RefreshTokens_UserId" ON auth."RefreshTokens" USING btree ("UserId");


--
-- TOC entry 4940 (class 1259 OID 18032)
-- Name: IX_TwoFactorCodes_TwoFactorStatusId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_TwoFactorCodes_TwoFactorStatusId" ON auth."TwoFactorCodes" USING btree ("TwoFactorStatusId");


--
-- TOC entry 4941 (class 1259 OID 18033)
-- Name: IX_TwoFactorCodes_UserId_Code; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_TwoFactorCodes_UserId_Code" ON auth."TwoFactorCodes" USING btree ("UserId", "Code");


--
-- TOC entry 4925 (class 1259 OID 18017)
-- Name: IX_Accounts_AccountTypeId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Accounts_AccountTypeId" ON finances."Accounts" USING btree ("AccountTypeId");


--
-- TOC entry 4926 (class 1259 OID 18018)
-- Name: IX_Accounts_BankId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Accounts_BankId" ON finances."Accounts" USING btree ("BankId");


--
-- TOC entry 4927 (class 1259 OID 18019)
-- Name: IX_Accounts_CurrecyId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Accounts_CurrecyId" ON finances."Accounts" USING btree ("CurrecyId");


--
-- TOC entry 4928 (class 1259 OID 18020)
-- Name: IX_Accounts_UserId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Accounts_UserId" ON finances."Accounts" USING btree ("UserId");


--
-- TOC entry 4931 (class 1259 OID 18021)
-- Name: IX_Categories_NatureId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Categories_NatureId" ON finances."Categories" USING btree ("NatureId");


--
-- TOC entry 4932 (class 1259 OID 18022)
-- Name: IX_Categories_ParentId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Categories_ParentId" ON finances."Categories" USING btree ("ParentId");


--
-- TOC entry 4933 (class 1259 OID 18023)
-- Name: IX_Categories_UserId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Categories_UserId" ON finances."Categories" USING btree ("UserId");


--
-- TOC entry 4917 (class 1259 OID 18031)
-- Name: IX_TransactionTypes_Code; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE UNIQUE INDEX "IX_TransactionTypes_Code" ON finances."TransactionTypes" USING btree ("Code");


--
-- TOC entry 4944 (class 1259 OID 18026)
-- Name: IX_Transactions_AccountId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Transactions_AccountId" ON finances."Transactions" USING btree ("AccountId");


--
-- TOC entry 4945 (class 1259 OID 18027)
-- Name: IX_Transactions_CategoryId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Transactions_CategoryId" ON finances."Transactions" USING btree ("CategoryId");


--
-- TOC entry 4946 (class 1259 OID 18028)
-- Name: IX_Transactions_Reference; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Transactions_Reference" ON finances."Transactions" USING btree ("Reference");


--
-- TOC entry 4947 (class 1259 OID 18029)
-- Name: IX_Transactions_TransactionTypeId; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Transactions_TransactionTypeId" ON finances."Transactions" USING btree ("TransactionTypeId");


--
-- TOC entry 4948 (class 1259 OID 18030)
-- Name: IX_Transactions_UserId_TransactionDate; Type: INDEX; Schema: finances; Owner: postgres
--

CREATE INDEX "IX_Transactions_UserId_TransactionDate" ON finances."Transactions" USING btree ("UserId", "TransactionDate");


--
-- TOC entry 4922 (class 1259 OID 18034)
-- Name: IX_Users_Email; Type: INDEX; Schema: users; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON users."Users" USING btree ("Email");


--
-- TOC entry 4958 (class 2606 OID 17952)
-- Name: RefreshTokens FK_RefreshTokens_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."RefreshTokens"
    ADD CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES users."Users"("UserId") ON DELETE CASCADE;


--
-- TOC entry 4959 (class 2606 OID 17970)
-- Name: TwoFactorCodes FK_TwoFactorCodes_TwoFactorStatus_TwoFactorStatusId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."TwoFactorCodes"
    ADD CONSTRAINT "FK_TwoFactorCodes_TwoFactorStatus_TwoFactorStatusId" FOREIGN KEY ("TwoFactorStatusId") REFERENCES auth."TwoFactorStatus"("TwoFactorStatusId") ON DELETE CASCADE;


--
-- TOC entry 4960 (class 2606 OID 17975)
-- Name: TwoFactorCodes FK_TwoFactorCodes_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."TwoFactorCodes"
    ADD CONSTRAINT "FK_TwoFactorCodes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES users."Users"("UserId") ON DELETE CASCADE;


--
-- TOC entry 4951 (class 2606 OID 17891)
-- Name: Accounts FK_Accounts_AccountTypes_AccountTypeId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Accounts"
    ADD CONSTRAINT "FK_Accounts_AccountTypes_AccountTypeId" FOREIGN KEY ("AccountTypeId") REFERENCES finances."AccountTypes"("AccountTypeId") ON DELETE CASCADE;


--
-- TOC entry 4952 (class 2606 OID 17896)
-- Name: Accounts FK_Accounts_Banks_BankId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Accounts"
    ADD CONSTRAINT "FK_Accounts_Banks_BankId" FOREIGN KEY ("BankId") REFERENCES finances."Banks"("BankId") ON DELETE CASCADE;


--
-- TOC entry 4953 (class 2606 OID 17901)
-- Name: Accounts FK_Accounts_Currencies_CurrecyId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Accounts"
    ADD CONSTRAINT "FK_Accounts_Currencies_CurrecyId" FOREIGN KEY ("CurrecyId") REFERENCES finances."Currencies"("CurrecyId") ON DELETE CASCADE;


--
-- TOC entry 4954 (class 2606 OID 17906)
-- Name: Accounts FK_Accounts_Users_UserId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Accounts"
    ADD CONSTRAINT "FK_Accounts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES users."Users"("UserId") ON DELETE CASCADE;


--
-- TOC entry 4955 (class 2606 OID 17924)
-- Name: Categories FK_Categories_Categories_ParentId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Categories"
    ADD CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES finances."Categories"("CategoryId") ON DELETE RESTRICT;


--
-- TOC entry 4956 (class 2606 OID 17929)
-- Name: Categories FK_Categories_Natures_NatureId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Categories"
    ADD CONSTRAINT "FK_Categories_Natures_NatureId" FOREIGN KEY ("NatureId") REFERENCES finances."Natures"("NatureId") ON DELETE CASCADE;


--
-- TOC entry 4957 (class 2606 OID 17934)
-- Name: Categories FK_Categories_Users_UserId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Categories"
    ADD CONSTRAINT "FK_Categories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES users."Users"("UserId") ON DELETE CASCADE;


--
-- TOC entry 4961 (class 2606 OID 17997)
-- Name: Transactions FK_Transactions_Accounts_AccountId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Transactions"
    ADD CONSTRAINT "FK_Transactions_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES finances."Accounts"("AccountId") ON DELETE CASCADE;


--
-- TOC entry 4962 (class 2606 OID 18002)
-- Name: Transactions FK_Transactions_Categories_CategoryId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Transactions"
    ADD CONSTRAINT "FK_Transactions_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES finances."Categories"("CategoryId") ON DELETE CASCADE;


--
-- TOC entry 4963 (class 2606 OID 18007)
-- Name: Transactions FK_Transactions_TransactionTypes_TransactionTypeId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Transactions"
    ADD CONSTRAINT "FK_Transactions_TransactionTypes_TransactionTypeId" FOREIGN KEY ("TransactionTypeId") REFERENCES finances."TransactionTypes"("TransactionTypeId") ON DELETE CASCADE;


--
-- TOC entry 4964 (class 2606 OID 18012)
-- Name: Transactions FK_Transactions_Users_UserId; Type: FK CONSTRAINT; Schema: finances; Owner: postgres
--

ALTER TABLE ONLY finances."Transactions"
    ADD CONSTRAINT "FK_Transactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES users."Users"("UserId") ON DELETE CASCADE;


-- Completed on 2026-03-16 06:31:30

--
-- PostgreSQL database dump complete
--

\unrestrict B7mXd0OzeRtiyxGyfitbnaAnPmWeGCuF0Ff9btookWpeDbxhuztW4vAhfyd3HnD

