// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316121655_new_initial_again_4times4")]
    partial class new_initial_again_4times4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RefreshTokenId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TwoFactorCodeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TwoFactorStatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TwoFactorStatusId");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("TwoFactorCodes", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorStatus", b =>
                {
                    b.Property<int>("TwoFactorStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TwoFactorStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TwoFactorStatusId");

                    b.ToTable("TwoFactorStatus", "auth");

                    b.HasData(
                        new
                        {
                            TwoFactorStatusId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TwoFactorStatusId = 2,
                            Status = "Used"
                        },
                        new
                        {
                            TwoFactorStatusId = 3,
                            Status = "Expired"
                        },
                        new
                        {
                            TwoFactorStatusId = 4,
                            Status = "Replaced"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountId");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrecyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrecyId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountTypeId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99f16153-db8f-412e-a7af-437fe62c7f33"),
                            Abbre = "TYPE-CASH",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(5471),
                            Name = "Cash"
                        },
                        new
                        {
                            Id = new Guid("33bd93c8-eec4-406a-9619-ff3af41bc799"),
                            Abbre = "TYPE-DEBT",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(5474),
                            Name = "Debit"
                        },
                        new
                        {
                            Id = new Guid("e635117b-0551-40fa-afb1-5389cfcd3ce2"),
                            Abbre = "TYPE-SAVS",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(5475),
                            Name = "Savings"
                        },
                        new
                        {
                            Id = new Guid("b1528456-c62e-4b45-9aa2-f9b8fa22bca0"),
                            Abbre = "TYPE-INVS",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(5476),
                            Name = "Investment"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BankId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TransferFee")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Banks", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ec5eab9-3a72-40b2-8746-b94e2ab3579b"),
                            Abbre = "BAC",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(3986),
                            Name = "BANCO DE AMERICA",
                            TransferFee = 2.0
                        },
                        new
                        {
                            Id = new Guid("90d3db5d-0c60-462a-93c9-3f0bd46c642f"),
                            Abbre = "BANPRO",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(3989),
                            Name = "BANCO DE LA PRODUCCION",
                            TransferFee = 2.0
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NatureId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CurrecyId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31e3c165-a6c6-4f84-9f6a-2159ba16a29e"),
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(4489),
                            Name = "Dolar Estadounidense",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("1424bdef-0fa6-4e2a-a52b-c6d43d25df96"),
                            Code = "NIO",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(4492),
                            Name = "Cordoba Nicaraguense",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = new Guid("f39e961f-b290-4559-91e5-2fe47e4e424d"),
                            Code = "EUR",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(4493),
                            Name = "Euro",
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Nature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NatureId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Natures", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4477b269-2acb-4649-9560-e9d09191b588"),
                            Abbre = "I",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(3519),
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("b1153a41-286d-4fe7-88da-1604d4ddf8ec"),
                            Abbre = "E",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(3523),
                            Name = "Expenses"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionId");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferGroupID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Reference");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId", "TransactionDate");

                    b.ToTable("Transactions", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1419b9a1-8119-418e-a679-90f4794b9b06"),
                            Code = "INC",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(5035),
                            CurrentValue = 0,
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("b158f17a-9967-434f-b5a9-3c499688966e"),
                            Code = "EXP",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(5039),
                            CurrentValue = 0,
                            Name = "Expenses"
                        },
                        new
                        {
                            Id = new Guid("959bde9a-1eb6-47e0-9977-fb10ebd606a4"),
                            Code = "TRF",
                            CreatedAt = new DateTime(2026, 3, 16, 12, 16, 55, 0, DateTimeKind.Utc).AddTicks(5041),
                            CurrentValue = 0,
                            Name = "Transfers"
                        });
                });

            modelBuilder.Entity("Domain.Features.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.HasOne("Domain.Features.Auth.Entities.TwoFactorStatus", "Status")
                        .WithMany()
                        .HasForeignKey("TwoFactorStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Currency", "Currecy")
                        .WithMany()
                        .HasForeignKey("CurrecyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Bank");

                    b.Navigation("Currecy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Nature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nature");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
