// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319203004_changin_properties_on_accounts")]
    partial class changin_properties_on_accounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RefreshTokenId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TwoFactorCodeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TwoFactorStatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TwoFactorStatusId");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("TwoFactorCodes", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorStatus", b =>
                {
                    b.Property<int>("TwoFactorStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TwoFactorStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TwoFactorStatusId");

                    b.ToTable("TwoFactorStatus", "auth");

                    b.HasData(
                        new
                        {
                            TwoFactorStatusId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TwoFactorStatusId = 2,
                            Status = "Used"
                        },
                        new
                        {
                            TwoFactorStatusId = 3,
                            Status = "Expired"
                        },
                        new
                        {
                            TwoFactorStatusId = 4,
                            Status = "Replaced"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountId");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountTypeId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c31315b3-6224-46e0-84c8-0e7c499be3fe"),
                            Abbre = "TYPE-CASH",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(6232),
                            Name = "Cash"
                        },
                        new
                        {
                            Id = new Guid("521c9407-50e0-41f9-a290-6cde61dd3022"),
                            Abbre = "TYPE-DEBT",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(6236),
                            Name = "Debit"
                        },
                        new
                        {
                            Id = new Guid("9f87bdfe-3dbc-4a36-99de-292fc37e8e15"),
                            Abbre = "TYPE-SAVS",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(6237),
                            Name = "Savings"
                        },
                        new
                        {
                            Id = new Guid("d96033f6-c162-4358-ad45-72cf7865500b"),
                            Abbre = "TYPE-INVS",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(6238),
                            Name = "Investment"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BankId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TransferFee")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Banks", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9e23ea2-e0eb-424f-b6bb-eaae490f5b2f"),
                            Abbre = "BAC",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(5676),
                            ImgURL = "",
                            Name = "BANCO DE AMERICA",
                            TransferFee = 2.0
                        },
                        new
                        {
                            Id = new Guid("46c12ec2-33df-474e-8b68-a6865b607cbe"),
                            Abbre = "BANPRO",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(5687),
                            ImgURL = "",
                            Name = "BANCO DE LA PRODUCCION",
                            TransferFee = 2.0
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NatureId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CurrecyId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79634f86-5443-4587-a011-a77be149c6b7"),
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(5881),
                            Name = "Dolar Estadounidense",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("1384921d-995c-4e6f-89bc-841c510985cd"),
                            Code = "NIO",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(5884),
                            Name = "Cordoba Nicaraguense",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = new Guid("a68369ca-2e8c-4c04-b809-cf80301e9889"),
                            Code = "EUR",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(5885),
                            Name = "Euro",
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Nature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NatureId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Natures", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c01e00c1-6a04-40fa-980e-007e219fdb52"),
                            Abbre = "I",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(5408),
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("3e492092-fa60-4e9e-bf6e-5bf479039b8f"),
                            Abbre = "E",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(5411),
                            Name = "Expenses"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionId");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferGroupID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Reference");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId", "TransactionDate");

                    b.ToTable("Transactions", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73b244ba-487e-4788-b4dc-de7aaad86e94"),
                            Code = "INC",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(6074),
                            CurrentValue = 0,
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("543f9de6-5a58-47a1-9cdc-2e0dba6ff5f4"),
                            Code = "EXP",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(6077),
                            CurrentValue = 0,
                            Name = "Expenses"
                        },
                        new
                        {
                            Id = new Guid("a4bda559-6628-4ff4-a261-f921c6cf86b5"),
                            Code = "TRF",
                            CreatedAt = new DateTime(2026, 3, 19, 20, 30, 3, 805, DateTimeKind.Utc).AddTicks(6077),
                            CurrentValue = 0,
                            Name = "Transfers"
                        });
                });

            modelBuilder.Entity("Domain.Features.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.HasOne("Domain.Features.Auth.Entities.TwoFactorStatus", "Status")
                        .WithMany()
                        .HasForeignKey("TwoFactorStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Bank");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Nature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nature");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
