// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319154340_adding_bankIMGURL")]
    partial class adding_bankIMGURL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RefreshTokenId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TwoFactorCodeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TwoFactorStatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TwoFactorStatusId");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("TwoFactorCodes", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorStatus", b =>
                {
                    b.Property<int>("TwoFactorStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TwoFactorStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TwoFactorStatusId");

                    b.ToTable("TwoFactorStatus", "auth");

                    b.HasData(
                        new
                        {
                            TwoFactorStatusId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TwoFactorStatusId = 2,
                            Status = "Used"
                        },
                        new
                        {
                            TwoFactorStatusId = 3,
                            Status = "Expired"
                        },
                        new
                        {
                            TwoFactorStatusId = 4,
                            Status = "Replaced"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountId");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrecyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrecyId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountTypeId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bec05ec-78ff-40f8-a2a6-4ac29343a89d"),
                            Abbre = "TYPE-CASH",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 889, DateTimeKind.Utc).AddTicks(8),
                            Name = "Cash"
                        },
                        new
                        {
                            Id = new Guid("9fc537e9-e19a-4fbc-9bf6-8b352f6e422b"),
                            Abbre = "TYPE-DEBT",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 889, DateTimeKind.Utc).AddTicks(10),
                            Name = "Debit"
                        },
                        new
                        {
                            Id = new Guid("4212447d-201e-4f41-b3c7-1b9381f2adc4"),
                            Abbre = "TYPE-SAVS",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 889, DateTimeKind.Utc).AddTicks(11),
                            Name = "Savings"
                        },
                        new
                        {
                            Id = new Guid("d408c707-19da-49ae-be14-6adff41d86f7"),
                            Abbre = "TYPE-INVS",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 889, DateTimeKind.Utc).AddTicks(12),
                            Name = "Investment"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BankId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TransferFee")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Banks", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("047b6804-9ec6-4a89-aff8-89b5dfd6aee6"),
                            Abbre = "BAC",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9437),
                            ImgURL = "",
                            Name = "BANCO DE AMERICA",
                            TransferFee = 2.0
                        },
                        new
                        {
                            Id = new Guid("9d69c4ce-92b9-4d89-95da-e7c0980429ec"),
                            Abbre = "BANPRO",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9441),
                            ImgURL = "",
                            Name = "BANCO DE LA PRODUCCION",
                            TransferFee = 2.0
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NatureId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CurrecyId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e57c7e1-6994-4107-b468-7cf991f82248"),
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9643),
                            Name = "Dolar Estadounidense",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("85b72c97-1e67-4494-83b5-caa8865f0d98"),
                            Code = "NIO",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9645),
                            Name = "Cordoba Nicaraguense",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = new Guid("22d4a305-7eff-443c-b489-04f3d91537c7"),
                            Code = "EUR",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9646),
                            Name = "Euro",
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Nature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NatureId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Natures", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("85183be1-d77e-4f0e-b1ad-1456a093c76b"),
                            Abbre = "I",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9210),
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("8e29b285-17dc-4c6a-8aeb-fd782fba09d3"),
                            Abbre = "E",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9212),
                            Name = "Expenses"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionId");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferGroupID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Reference");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId", "TransactionDate");

                    b.ToTable("Transactions", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47d09d9-bfee-4b9b-a26b-0830a01a56c8"),
                            Code = "INC",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9849),
                            CurrentValue = 0,
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("8eab2ce2-994f-41a7-825f-08821fa1429a"),
                            Code = "EXP",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9851),
                            CurrentValue = 0,
                            Name = "Expenses"
                        },
                        new
                        {
                            Id = new Guid("c20d8bc6-252f-4a2b-b145-01419ec5be12"),
                            Code = "TRF",
                            CreatedAt = new DateTime(2026, 3, 19, 15, 43, 39, 888, DateTimeKind.Utc).AddTicks(9852),
                            CurrentValue = 0,
                            Name = "Transfers"
                        });
                });

            modelBuilder.Entity("Domain.Features.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.HasOne("Domain.Features.Auth.Entities.TwoFactorStatus", "Status")
                        .WithMany()
                        .HasForeignKey("TwoFactorStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Currency", "Currecy")
                        .WithMany()
                        .HasForeignKey("CurrecyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Bank");

                    b.Navigation("Currecy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Nature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nature");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
