// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316210247_initalMigration2")]
    partial class initalMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RefreshTokenId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TwoFactorCodeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TwoFactorStatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TwoFactorStatusId");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("TwoFactorCodes", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorStatus", b =>
                {
                    b.Property<int>("TwoFactorStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TwoFactorStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TwoFactorStatusId");

                    b.ToTable("TwoFactorStatus", "auth");

                    b.HasData(
                        new
                        {
                            TwoFactorStatusId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TwoFactorStatusId = 2,
                            Status = "Used"
                        },
                        new
                        {
                            TwoFactorStatusId = 3,
                            Status = "Expired"
                        },
                        new
                        {
                            TwoFactorStatusId = 4,
                            Status = "Replaced"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountId");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrecyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrecyId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountTypeId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7e7b6f5-6999-4cf3-9ef8-518286f8112f"),
                            Abbre = "TYPE-CASH",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1793),
                            Name = "Cash"
                        },
                        new
                        {
                            Id = new Guid("7413b614-58ae-4922-a22d-840e7bf1d03f"),
                            Abbre = "TYPE-DEBT",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1795),
                            Name = "Debit"
                        },
                        new
                        {
                            Id = new Guid("3dad54c6-e5b1-4b7f-a678-efcc24a73983"),
                            Abbre = "TYPE-SAVS",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1796),
                            Name = "Savings"
                        },
                        new
                        {
                            Id = new Guid("1dffc8a4-e24f-418f-a9f5-adaccd8455b7"),
                            Abbre = "TYPE-INVS",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1797),
                            Name = "Investment"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BankId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TransferFee")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Banks", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ee53578-d602-4d37-80f2-9ac964a3e830"),
                            Abbre = "BAC",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1142),
                            Name = "BANCO DE AMERICA",
                            TransferFee = 2.0
                        },
                        new
                        {
                            Id = new Guid("70bae19e-36f3-4a70-8783-162036b33abe"),
                            Abbre = "BANPRO",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1144),
                            Name = "BANCO DE LA PRODUCCION",
                            TransferFee = 2.0
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NatureId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CurrecyId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b8ba4a4-3497-41ef-bcb7-d0d3cc07fa93"),
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1375),
                            Name = "Dolar Estadounidense",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("0e9f724a-9dc4-4b50-bf14-fc5263e1a65d"),
                            Code = "NIO",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1377),
                            Name = "Cordoba Nicaraguense",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = new Guid("281a09b0-8a1f-4478-89b9-06a72ca7ee37"),
                            Code = "EUR",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1378),
                            Name = "Euro",
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Nature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NatureId");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Natures", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59fd5203-4fe3-45e2-ace3-dae0ec68a99c"),
                            Abbre = "I",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(870),
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("e5f74b3c-2db7-447b-947d-640f676a5379"),
                            Abbre = "E",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(872),
                            Name = "Expenses"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionId");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferGroupID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Reference");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId", "TransactionDate");

                    b.ToTable("Transactions", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("faa47c1b-c0de-413a-9130-7a18f58b922a"),
                            Code = "INC",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1633),
                            CurrentValue = 0,
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("5bd8825b-0990-4a15-99ed-f7570513cb77"),
                            Code = "EXP",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1638),
                            CurrentValue = 0,
                            Name = "Expenses"
                        },
                        new
                        {
                            Id = new Guid("8e27b508-f3cd-4d04-966e-71503a8a9287"),
                            Code = "TRF",
                            CreatedAt = new DateTime(2026, 3, 16, 21, 2, 46, 586, DateTimeKind.Utc).AddTicks(1639),
                            CurrentValue = 0,
                            Name = "Transfers"
                        });
                });

            modelBuilder.Entity("Domain.Features.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.HasOne("Domain.Features.Auth.Entities.TwoFactorStatus", "Status")
                        .WithMany()
                        .HasForeignKey("TwoFactorStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Currency", "Currecy")
                        .WithMany()
                        .HasForeignKey("CurrecyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Bank");

                    b.Navigation("Currecy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Nature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nature");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
