// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RefreshTokenID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TwoFactorCodeID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TwoFactorStatusID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TwoFactorStatusID");

                    b.HasIndex("UserID", "Code");

                    b.ToTable("TwoFactorCodes", "auth");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorStatus", b =>
                {
                    b.Property<int>("TwoFactorStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TwoFactorStatusID"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TwoFactorStatusID");

                    b.ToTable("TwoFactorStatus", "auth");

                    b.HasData(
                        new
                        {
                            TwoFactorStatusID = 1,
                            Status = "Active"
                        },
                        new
                        {
                            TwoFactorStatusID = 2,
                            Status = "Used"
                        },
                        new
                        {
                            TwoFactorStatusID = 3,
                            Status = "Expired"
                        },
                        new
                        {
                            TwoFactorStatusID = 4,
                            Status = "Replaced"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountID");

                    b.Property<Guid>("AccountTypeID")
                        .HasColumnType("uuid");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BankID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrecyID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeID");

                    b.HasIndex("BankID");

                    b.HasIndex("CurrecyID");

                    b.HasIndex("UserID");

                    b.ToTable("Accounts", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AccountTypeID");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("BankID");

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("BankID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TransferFee")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Banks", "finances", t =>
                        {
                            t.Property("BankID")
                                .HasColumnName("BankID1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7abf0c4-95bd-4bcd-baae-731fbd1727a6"),
                            Abbre = "BAC",
                            BankID = new Guid("b7abf0c4-95bd-4bcd-baae-731fbd1727a6"),
                            CreatedAt = new DateTime(2026, 3, 6, 21, 33, 1, 176, DateTimeKind.Utc).AddTicks(9860),
                            Name = "BANCO DE AMERICA",
                            TransferFee = 2.0
                        },
                        new
                        {
                            Id = new Guid("03762b24-f0f0-458e-8ddc-d00820fa0a3b"),
                            Abbre = "BANPRO",
                            BankID = new Guid("03762b24-f0f0-458e-8ddc-d00820fa0a3b"),
                            CreatedAt = new DateTime(2026, 3, 6, 21, 33, 1, 176, DateTimeKind.Utc).AddTicks(9863),
                            Name = "BANCO DE LA PRODUCCION",
                            TransferFee = 2.0
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NatureID")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NatureID");

                    b.HasIndex("ParentID");

                    b.HasIndex("UserID");

                    b.ToTable("Categories", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CurrecyID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Nature", b =>
                {
                    b.Property<int>("NatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NatureID"));

                    b.Property<string>("Abbre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NatureID");

                    b.ToTable("Natures", "finances");

                    b.HasData(
                        new
                        {
                            NatureID = 1,
                            Abbre = "I",
                            Name = "Income"
                        },
                        new
                        {
                            NatureID = 2,
                            Abbre = "E",
                            Name = "Expenses"
                        });
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionID");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionTypeID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferGroupID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("Reference");

                    b.HasIndex("TransactionTypeID");

                    b.HasIndex("UserID", "TransactionDate");

                    b.ToTable("Transactions", "finances");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionTypeID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionTypes", "finances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1886992-b77c-4457-b086-363d91e60e2d"),
                            Code = "INC",
                            CreatedAt = new DateTime(2026, 3, 6, 21, 33, 1, 177, DateTimeKind.Utc).AddTicks(230),
                            CurrentValue = 0,
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("2b0c0912-5e45-48c7-8a4a-5d84045c2be1"),
                            Code = "EXP",
                            CreatedAt = new DateTime(2026, 3, 6, 21, 33, 1, 177, DateTimeKind.Utc).AddTicks(232),
                            CurrentValue = 0,
                            Name = "Expenses"
                        },
                        new
                        {
                            Id = new Guid("03de4a68-0315-4983-98da-2fac844af230"),
                            Code = "TRF",
                            CreatedAt = new DateTime(2026, 3, 6, 21, 33, 1, 177, DateTimeKind.Utc).AddTicks(233),
                            CurrentValue = 0,
                            Name = "Transfers"
                        });
                });

            modelBuilder.Entity("Domain.Features.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Features.Auth.Entities.TwoFactorCode", b =>
                {
                    b.HasOne("Domain.Features.Auth.Entities.TwoFactorStatus", "Status")
                        .WithMany()
                        .HasForeignKey("TwoFactorStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Account", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Currency", "Currecy")
                        .WithMany()
                        .HasForeignKey("CurrecyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("Bank");

                    b.Navigation("Currecy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Category", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Nature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nature");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Finances.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Features.Finances.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Finances.Entities.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Features.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
