@GastiGo.API_HostAddress = http://localhost:5094


POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{

  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": null,
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Salario",
  "description": "Salario otorgado mensualmente"
}

###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": null,
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Inversión",
  "description": "Entrada por inversión"
}

###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": null,
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Discrecional",
  "description": "Otros tipos de entrada"
}

###




POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "4d97e145-8267-4c93-b95a-50f3602427ba",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Salario Básico",
  "description": "Salario básico mensual de ISSDHU"
}

###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "4d97e145-8267-4c93-b95a-50f3602427ba",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Salario Bruto",
  "description": "Salario bruto de ISSDHU"
}

###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "4d97e145-8267-4c93-b95a-50f3602427ba",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Salario Neto",
  "description": "Salario neto de ISSDHU despues de deducciones"
}

###


POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "4d97e145-8267-4c93-b95a-50f3602427ba",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Porcentaje por titulo",
  "description": "Porcentaje por titulo de posgrado 13%"
}

###

 POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "4d97e145-8267-4c93-b95a-50f3602427ba",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Viatico de alimentación",
  "description": "Viático de alimentación proporcionado como bono"
}

###

  
 POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "4d97e145-8267-4c93-b95a-50f3602427ba",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Antiguedad",
  "description": "Años de servicio en la compania desde agosto 2016"
}


### Inversiones
 POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "362175c2-2115-48c4-bf2f-779de40a4d3c",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Dividendos Invercasa",
  "description": "Dividendos proveniente de Invercasa 6% - 8%"
}

###

   POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "362175c2-2115-48c4-bf2f-779de40a4d3c",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Dividendos Bancarios",
  "description": "Dividendos proveniente de BAC 2% anual"
}

###  Discrecional
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "362175c2-2115-48c4-bf2f-779de40a4d3c",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Viáticos",
  "description": "Viáticos de alimento y transporte"
}

###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "362175c2-2115-48c4-bf2f-779de40a4d3c",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Regalos",
  "description": "Dinero extra por obsequios"
}

###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "362175c2-2115-48c4-bf2f-779de40a4d3c",
  "natureID": "f1e9c692-e70c-4e5c-92a2-6908fe750f39",
  "name": "Freelance",
  "description": "Otros trabajos fuera de mi horario"
}

### GASTOS


POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
 
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": null,
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Gastos Esenciales",
  "description": "Gastos esenciales para subsistir"
}
###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": null,
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Gastos Fijos",
  "description": "Gastos fijos que se debe de pagar"
}

###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": null,
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Gastos Discrecional",
  "description": "Gastos no esenciales, facil de vivir si eso"
}

### pagos esenciales
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "83c16ada-244d-47f3-9b2c-1dc4edd8579e",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Alimentación",
  "description": "Gasto para la comida del hogar"
}
###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "83c16ada-244d-47f3-9b2c-1dc4edd8579e",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Servicio eléctrico",
  "description": "Pago de factura de luz"
}
###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "83c16ada-244d-47f3-9b2c-1dc4edd8579e",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Servicio de internet",
  "description": "Pago de factura de internet"
}
###

POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "83c16ada-244d-47f3-9b2c-1dc4edd8579e",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Servicio de internet telefono",
  "description": "Pago de internet telefono"
}
###


POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "83c16ada-244d-47f3-9b2c-1dc4edd8579e",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Medicamentos",
  "description": "Compra de medicamentos"
}
###


POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "83c16ada-244d-47f3-9b2c-1dc4edd8579e",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Pasaje de autobus",
  "description": "Pago de pasaje de bus, ida y vuelta"
}
###


POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "83c16ada-244d-47f3-9b2c-1dc4edd8579e",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Mantenimiento",
  "description": "Pago de reparaciones del hogar"
}




### pago fijos
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
 
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "2eba37bf-4bb9-4a19-998e-7aea9b3932bc",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Seguro INSS",
  "description": "Pago de seguro laboral 7%"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "2eba37bf-4bb9-4a19-998e-7aea9b3932bc",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "IR",
  "description": "Pago de la mayor estafa del pais, IR"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "2eba37bf-4bb9-4a19-998e-7aea9b3932bc",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Préstamos",
  "description": "Préstamos adquiridos en bancos"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "2eba37bf-4bb9-4a19-998e-7aea9b3932bc",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Seguro de tarjeta de débito/crédito",
  "description": "Seguro de tarjetas bancarias"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "2eba37bf-4bb9-4a19-998e-7aea9b3932bc",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Pago de lotes",
  "description": "Pago mensual para la adquisición de lotes"
}




### gastos no esenciales
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Taxi",
  "description": "Pago de taxi"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Tarifa",
  "description": "Cualquier tipo de tarifa por transacción"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Compras supermercado",
  "description": "Compra de supermercado para uso persona"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Asistencia",
  "description": "Asistencia de tercero como plancha, lavado, etc"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Salida al cine",
  "description": "Salida al cine, incluye palomitas y soda"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Comida afuera",
  "description": "Comida en fritanga, restaurantes, hoteles"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Snacks",
  "description": "Chiverias"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Apuestas",
  "description": "Apuestar perdidas"
}


###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Ropa",
  "description": "Compra de piezas ropa"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Libros",
  "description": "Compra de Libros"
}


###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json
{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Celebraciones",
  "description": "Participacion de celebraciones"
}




###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Cosmetico y belleza",
  "description": "Productos de cosmetica y cuidado personal"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Corte de pelo",
  "description": "Servicios de barberia o peluqueria"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Viajes",
  "description": "Gastos relacionados con viajes y turismo"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Videojuegos",
  "description": "Compra de videojuegos y servicios relacionados"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Cursos",
  "description": "Cursos, capacitaciones y educacion"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Muebles y Hogar",
  "description": "Compra de muebles y articulos para el hogar"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Tecnologia",
  "description": "Compra de dispositivos y tecnologia"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Zanganaderia",
  "description": "Servicios personales"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Otros servicios",
  "description": "Otros servicios no clasificados"
}

###
POST {{GastiGo.API_HostAddress}}/api/finance/categories
Content-Type: application/json

{
  
  "userID": "c502b17e-a322-4df7-ad25-75a11bc2ac2d",
  "parentID": "aabd7486-6f93-43fe-b64d-23206b8af763",
  "natureID": "129a7622-4437-42d1-8e16-0e9ce1a65e2e",
  "name": "Ayudas económicas",
  "description": "Actos de filantropia"
}









